#!/usr/bin/env python3
"""
scaffold.py — create a DUMMY ServiceNow Fluent app scaffold, then merge a
docx_to_build_agent.py package into it as a "sidecar":

  - the .md spec goes to <target>/GUIDE_<slug>.md (project root), matching
    ServiceNow's own documented Build Agent grounding-file convention
    ("Place a markdown file, for example named GUIDE_*.md or
    BUILD_AGENT_RULES.md, in your project directory. Build Agent reads these
    grounding files and follows your conventions throughout the session.")
  - images/ and embedded-data/ go to <target>/docs/, with the guide file's
    relative links rewritten to match

DISCLAIMER: this scaffold is hand-written to mirror the file structure that
`npx @servicenow/sdk init --template typescript.basic` produces on
@servicenow/sdk 4.8.1 — it does NOT call `now-sdk init` and never contacts a
ServiceNow instance. The scopeId in now.config.json is a locally-generated
random value, not one registered against any instance. Why: `now-sdk init`
always tries to log into an instance to register the scope (confirmed by
testing — it does this even with no --auth flag given, falling back to
whatever alias is marked default), and this scaffold is meant to be a dummy
placeholder for Build Agent to read from, not a real app registration.

What's still genuine: `now-sdk build` (via `npm run build` / verify_build())
is the real SDK compiling the real Fluent files — confirmed by testing that
it succeeds with zero auth configured and zero instance contact. Only
`init`'s scope-registration step needed an instance; `build`'s verification
does not. So this scaffold is unregistered but still genuinely SDK-verified
as buildable, not hand-approximated in the sense that matters.

Only the typescript.basic template is supported by this hand-written path —
its exact file contents were captured from a real `now-sdk init` run and are
reproduced here verbatim as boilerplate. Other templates would need their
own captured boilerplate to support the same way.
"""
from __future__ import annotations

import re
import secrets
import subprocess
import sys
from pathlib import Path

VALID_TEMPLATES = {"typescript.basic"}

_GITIGNORE = """.DS_Store
.now/
dist/
node_modules/
target/
*.tsbuildinfo
.jest_cache
"""

_VSCODE_EXTENSIONS = """{
    "recommendations": [
        "servicenow.fluent-language-extension"
    ]
}
"""

_TSCONFIG_ROOT = """{
    "files": [],
    "references": [
        {
            "path": "./tsconfig.server.json"
        },
        {
            "path": "./tsconfig.client.json"
        }
    ]
}
"""

_TSCONFIG_CLIENT = """{
    "compilerOptions": {
        "target": "ES6",
        "lib": [
            "DOM",
            "ES6"
        ],
        "checkJs": true,
        "allowJs": true,
        "noEmit": true,
        "noEmitHelpers": true,
        "esModuleInterop": false,
        "module": "None",
        "types": []
    },
    "include": [
        "./**/*.client.js",
        "../@types/servicenow/*.client.d.ts"
    ]
}
"""

_TSCONFIG_SERVER = """{
    "compilerOptions": {
        "lib": [
            "ES2021"
        ],
        "noEmit": true,
        "checkJs": true,
        "allowJs": true,
        "noEmitHelpers": true,
        "esModuleInterop": false,
        "module": "None",
        "types": []
    },
    "include": [
        "./**/*.server.js",
        "../@types/servicenow/*.server.d.ts"
    ]
}
"""

_SERVER_TSCONFIG = """{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "strict": true,
    "skipLibCheck": true
  }
}
"""

_EXAMPLE_FLUENT = """import { BusinessRule, ClientScript } from '@servicenow/sdk/core'
import { showStateUpdate } from '../server/script'

// creates a client script that pops up 'Table loaded successfully!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!!")
    }`,
})

// creates a business rule that pops up state change message whenever a todo record is updated
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
})
"""

_SERVER_SCRIPT = """import { gs, type GlideRecord } from '@servicenow/glide'

export function showStateUpdate(current: GlideRecord, previous: GlideRecord) {
    const currentState = current.getValue('state')
    const previousState = previous.getValue('state')

    gs.addInfoMessage(`state updated from "${previousState}" to "${currentState}"`)
}
"""


def die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def create_fluent_scaffold(target_dir: Path, app_name: str, scope_name: str,
                            package_name: str = None, template: str = "typescript.basic",
                            skip_install: bool = False, **_ignored) -> Path:
    """Hand-write a dummy Fluent scaffold. No instance contact, no auth needed.
    `**_ignored` absorbs the old auth_alias/env_path kwargs so callers that
    still pass them don't break; they're no-ops now."""
    if template not in VALID_TEMPLATES:
        die(f"Invalid template {template!r}. Only {sorted(VALID_TEMPLATES)} is supported "
            f"by the hand-written scaffold path.")
    if len(scope_name) > 18:
        die(f"Scope name {scope_name!r} is {len(scope_name)} chars — must be <= 18.")

    target_dir.mkdir(parents=True, exist_ok=True)
    if (target_dir / "now.config.json").exists():
        die(f"{target_dir} already has a now.config.json — refusing to overwrite an existing scaffold.")

    package_name = package_name or re.sub(r"[^a-z0-9-]+", "-", app_name.lower()).strip("-")
    scope_id = secrets.token_hex(16)  # locally generated, NOT registered on any instance

    (target_dir / "src" / "fluent").mkdir(parents=True, exist_ok=True)
    (target_dir / "src" / "server").mkdir(parents=True, exist_ok=True)
    (target_dir / ".vscode").mkdir(parents=True, exist_ok=True)

    (target_dir / "now.config.json").write_text(
        f'{{\n'
        f'  "scope": "{scope_name}",\n'
        f'  "scopeId": "{scope_id}",\n'
        f'  "name": "{app_name}",\n'
        f'  "tsconfigPath": "./src/server/tsconfig.json"\n'
        f'}}\n', encoding="utf-8")

    (target_dir / "package.json").write_text(
        f'{{\n'
        f'  "name": "{package_name}",\n'
        f'  "version": "0.0.1",\n'
        f'  "description": "",\n'
        f'  "license": "UNLICENSED",\n'
        f'  "imports": {{\n'
        f'    "#now:*": "./@types/servicenow/fluent/*/index.js"\n'
        f'  }},\n'
        f'  "scripts": {{\n'
        f'    "build": "now-sdk build",\n'
        f'    "deploy": "now-sdk install",\n'
        f'    "transform": "now-sdk transform",\n'
        f'    "types": "now-sdk dependencies"\n'
        f'  }},\n'
        f'  "devDependencies": {{\n'
        f'    "@servicenow/sdk": "4.8.1",\n'
        f'    "@servicenow/glide": "27.0.5",\n'
        f'    "typescript": "5.5.4"\n'
        f'  }}\n'
        f'}}\n', encoding="utf-8")

    (target_dir / ".gitignore").write_text(_GITIGNORE, encoding="utf-8")
    (target_dir / ".vscode" / "extensions.json").write_text(_VSCODE_EXTENSIONS, encoding="utf-8")
    (target_dir / "src" / "tsconfig.json").write_text(_TSCONFIG_ROOT, encoding="utf-8")
    (target_dir / "src" / "tsconfig.client.json").write_text(_TSCONFIG_CLIENT, encoding="utf-8")
    (target_dir / "src" / "tsconfig.server.json").write_text(_TSCONFIG_SERVER, encoding="utf-8")
    (target_dir / "src" / "server" / "tsconfig.json").write_text(_SERVER_TSCONFIG, encoding="utf-8")
    (target_dir / "src" / "fluent" / "example.now.ts").write_text(_EXAMPLE_FLUENT, encoding="utf-8")
    (target_dir / "src" / "server" / "script.ts").write_text(_SERVER_SCRIPT, encoding="utf-8")

    print(f"Hand-written scaffold created at {target_dir} (scope={scope_name}, "
          f"scopeId={scope_id} — locally generated, not registered on any instance)")

    if not skip_install:
        print("Running npm install...")
        proc = subprocess.run(["npm", "install"], cwd=target_dir, capture_output=True, text=True)
        if proc.returncode != 0:
            die(f"npm install failed:\n{proc.stderr}")

    return target_dir


def verify_build(target_dir: Path) -> bool:
    """Runs the REAL `now-sdk build` — genuine SDK verification, confirmed by
    testing to require zero instance contact and zero auth configuration."""
    proc = subprocess.run(["npm", "run", "build"], cwd=target_dir, capture_output=True, text=True)
    print(proc.stdout)
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
    return proc.returncode == 0


def assemble_sidecar(package_dir: Path, target_dir: Path, guide_name: str = None) -> Path:
    """Merge a docx_to_build_agent package into a Fluent scaffold as a sidecar."""
    import shutil

    md_files = [f for f in package_dir.glob("*.md") if f.name != "UPLOAD-TO-BUILD-AGENT.md"]
    if not md_files:
        die(f"No spec .md found directly inside {package_dir}.")
    spec_md = md_files[0]

    guide_name = guide_name or f"GUIDE_{re.sub(r'[^A-Za-z0-9]+', '_', spec_md.stem).strip('_')}.md"
    guide_path = target_dir / guide_name

    text = spec_md.read_text(encoding="utf-8")
    text = re.sub(r'\((images/[^)]+)\)', r'(docs/\1)', text)
    text = re.sub(r'`embedded-data/', r'`docs/embedded-data/', text)
    guide_path.write_text(text, encoding="utf-8")

    docs_dir = target_dir / "docs"
    images_src = package_dir / "images"
    data_src = package_dir / "embedded-data"
    if images_src.exists() and any(images_src.iterdir()):
        dest = docs_dir / "images"
        dest.mkdir(parents=True, exist_ok=True)
        for f in images_src.glob("*"):
            shutil.copy2(f, dest / f.name)
    if data_src.exists() and any(data_src.iterdir()):
        dest = docs_dir / "embedded-data"
        dest.mkdir(parents=True, exist_ok=True)
        for f in data_src.glob("*.csv"):
            shutil.copy2(f, dest / f.name)

    print(f"Sidecar assembled: {guide_path.relative_to(target_dir)}, "
          f"docs/images ({len(list((docs_dir/'images').glob('*')) if (docs_dir/'images').exists() else [])} files), "
          f"docs/embedded-data ({len(list((docs_dir/'embedded-data').glob('*')) if (docs_dir/'embedded-data').exists() else [])} files)")
    return guide_path
